# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-06-27 10:19:30 -0400 by graham.troyer-joy:
gem "pry", "~> 0.11.3"
